server:
  port: 8085
spring:
  boot:
    admin:
      client:
        url: http://localhost:8091
  application:
    name: order-client
kafka:
  bootstrapAddress: localhost:9092
  acks: all
  retries: 5
  retry:
    backoff:
      ms: 1000
  message:
    exchangeEventTopic:
      name: exchange-events
